[package]
name = "dicetest-derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.87.0"
description = "Derive macro for dicetest"
readme = "README.md"
repository = "https://github.com/jakoschiko/dicetest-derive"
license = "MIT OR Apache-2.0"
keywords = ["dicetest"]
categories = ["development-tools::testing"]

[lib]
proc-macro = true

[dependencies]
darling = "0.21.3"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.109"
