[package]
name = "dicetest-derive"
version = "0.1.0"
authors = ["Jakob Schikowski"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Derive macro for dicetest"
keywords = ["dicetest"]
categories = ["development-tools::testing"]
repository = "https://github.com/jakoschiko/dicetest-derive"
edition = "2021"

[dependencies]
